[project]
name = "OpenStudioLandscapes-LikeC4"
description = "LikeC4 Feature for OpenStudioLandscapes"

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes-LikeC4"

[project.optional-dependencies]
sbom = [
    "OpenStudioLandscapes-LikeC4[graphviz]",
]
nox = [
    "OpenStudioLandscapes-LikeC4[testing]",
]
dev = [
    "OpenStudioLandscapes-LikeC4[testing]",
    "OpenStudioLandscapes-LikeC4[lint]",
    "OpenStudioLandscapes-LikeC4[nox]",
    "OpenStudioLandscapes-LikeC4[sbom]",
    "OpenStudioLandscapes-LikeC4[coverage]",
    "OpenStudioLandscapes-LikeC4[readme]",
]

# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration
[tool.setuptools]
packages = [
    "OpenStudioLandscapes.LikeC4"
]

[tool.dagster]
module_name = "OpenStudioLandscapes.LikeC4.definitions"
code_location_name = "OpenStudioLandscapes-LikeC4"
