# Base Information
group_name: "OpenStudioLandscapes_LikeC4"
key_prefixes:
  - "OpenStudioLandscapes_LikeC4"

#compose_scope: "default"

#enabled: true

#likec4_docker_image: "docker.io/likec4/likec4"

#likec4_LIKEC4_DEV_PORT_HOST: 5173
#likec4_LIKEC4_DEV_PORT_CONTAINER: 5173
#likec4_LIKEC4_RT_DEV_PORT_HOST: 24678
#likec4_LIKEC4_RT_DEV_PORT_CONTAINER: 24678

#likec4_LIKEC4_CHOKIDAR_USEPOLLING: 1
#likec4_LIKEC4_CHOKIDAR_INTERVAL: 200

#likec4_DATA_ROOT: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/data"

#likec4_sources: "https://github.com/likec4/likec4/archive/refs/tags/v1.46.3.tar.gz"
